#!/bin/bash
mkdir -p ~/.vim/bundle
git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
git clone https://github.com/Shougo/vimproc.git  ~/.vim/bundle/vimproc
cp post-merge ~/.vim/bundle/vimproc/.git/hooks/
cd ~/.vim/bundle/vimproc
git pull
cd -
mv ~/.vimrc ~/.vimrc.old
cp ./vimrc ~/.vimrc
echo ''
echo 'run vim, Esc-: NeoBundleInstall! '
echo 'your old .vimrc moved ~/.vimrc.old'
echo ''
